/**
 * A read-only Set containing all PHP reserved keywords and predefined types.
 * This includes both language syntax keywords and built-in types used in type hints.
 * Using a Set provides faster lookups (O(1)) than arrays and guarantees uniqueness.
 */
export const ReservedKeywords = new Set<string>([
    // Standard language keywords
    "abstract",
    "and",
    "array",
    "as",
    "break",
    "callable",
    "case",
    "catch",
    "class",
    "clone",
    "const",
    "continue",
    "declare",
    "default",
    "die",
    "do",
    "echo",
    "else",
    "elseif",
    "empty",
    "enddeclare",
    "endfor",
    "endforeach",
    "endif",
    "endswitch",
    "endwhile",
    "eval",
    "exit",
    "extends",
    "final",
    "finally",
    "fn",
    "for",
    "foreach",
    "function",
    "global",
    "goto",
    "if",
    "implements",
    "include",
    "include_once",
    "instanceof",
    "insteadof",
    "interface",
    "isset",
    "list",
    "match",
    "namespace",
    "new",
    "or",
    "print",
    "private",
    "protected",
    "public",
    "require",
    "require_once",
    "return",
    "static",
    "switch",
    "throw",
    "trait",
    "try",
    "unset",
    "use",
    "var",
    "while",
    "xor",
    "yield",
    "enum",
    "from",
    "as",

    // Predefined scalar types
    "bool",
    "boolean",
    "int",
    "integer",
    "float",
    "double",
    "string",

    // Special return/parameter types
    "void",
    "never",
    "mixed",
    "null",

    // Compound types
    "array",
    "object",
    "resource",
    "callable",
    "iterable",

    // Self-references
    "self",
    "parent",
    "static",
    "this",

    // PHP internal special types
    "__php_incomplete_class",

    // PHP magic methods
    "__construct",
    "__destruct",
    "__call",
    "__callstatic",
    "__get",
    "__set",
    "__isset",
    "__unset",
    "__sleep",
    "__wakeup",
    "__serialize",
    "__unserialize",
    "__toString",
    "__invoke",
    "__set_state",
    "__clone",
    "__debuginfo",

    // PHP magic constants (using lowercase for consistency with string comparison)
    "__line__",
    "__file__",
    "__dir__",
    "__function__",
    "__class__",
    "__trait__",
    "__method__",
    "__namespace__",

    // PHP attributes (since PHP 8.0)
    "attribute",
    "deprecated",
    "allowdynamicproperties",
    "sensitiveparameter",

    // PHP 8.2+ features
    "dnf",
    "readonly",
    "override",
    "true",
    "false",

    // PHPStan/Psalm specific pseudo-types (commonly used in docblocks)
    "class-string",
    "callable-string",
    "numeric-string",
    "list",
    "non-empty-array",
    "non-empty-list",
    "positive-int",
    "negative-int",
    "non-zero-int",
    "literal-string",
    "lowercase-string",
    "non-empty-string",
    "numeric",
    "scalar",
    "array-key",
]);
