/**
 * A read-only Set containing common PHP global functions that can be used without namespace qualification.
 * This particularly includes debug functions from Symfony/Laravel and built-in PHP functions
 * that are commonly used without namespace qualification.
 */
export const GlobalFunctions = Object.freeze(
    new Set<string>([
        // Debug functions (Symfony/Laravel)
        "dump",
        "dd",
        "var_dump",
        "print_r",

        // Array functions
        "array_map",
        "array_filter",
        "array_reduce",
        "array_merge",
        "in_array",
        "array_key_exists",
        "array_keys",
        "array_values",
        "array_push",
        "array_pop",
        "array_shift",
        "array_unshift",
        "array_slice",
        "array_splice",
        "array_chunk",
        "array_column",
        "array_combine",
        "array_diff",
        "array_intersect",
        "array_search",
        "array_sum",
        "array_unique",
        "sort",
        "asort",
        "rsort",
        "arsort",
        "ksort",
        "krsort",
        "shuffle",
        "array_walk",
        "array_fill",
        "range",
        "sizeof",
        "current",
        "next",
        "prev",
        "end",
        "reset",

        // String functions
        "str_replace",
        "str_contains",
        "str_starts_with",
        "str_ends_with",
        "strcmp",
        "strncmp",
        "strcasecmp",
        "strncasecmp",
        "strpos",
        "strrpos",
        "stripos",
        "strripos",
        "strstr",
        "stristr",
        "strrchr",
        "substr_count",
        "wordwrap",
        "htmlspecialchars",
        "htmlentities",
        "nl2br",
        "md5",
        "sha1",
        "password_hash",
        "password_verify",
        "implode",
        "explode",
        "trim",
        "ltrim",
        "rtrim",
        "strlen",
        "substr",
        "strtolower",
        "strtoupper",

        // JSON functions
        "json_encode",
        "json_decode",
        
        // RegExp functions
        "preg_match",
        "preg_replace",
        
        // File functions
        "file_get_contents",
        "file_put_contents",
        "fopen",
        "fclose",
        "fread",
        "fwrite",
        "fseek",
        "ftell",
        "file",
        "file_exists",
        "filesize",
        "is_file",
        "is_dir",
        "unlink",
        "rename",
        "mkdir",
        "rmdir",
        "dirname",
        "basename",
        "pathinfo",
        "glob",
        "scandir",
        
        // Type checking functions
        "count",
        "isset",
        "empty",
        "is_null",
        "is_array",
        "is_object",
        "is_string",
        "is_int",
        "is_float",
        "is_bool",
        "is_callable",
        "is_countable",
        "is_double",
        "is_iterable",
        "is_long",
        "is_numeric",
        "is_resource",
        "is_scalar",
        "is_subclass_of",
        "get_class",
        "get_object_vars",
        "method_exists",
        "property_exists",
        
        // Date/Time functions
        "time",
        "date",
        "strtotime",
        "mktime",
        "date_create",
        "date_format",
        "date_add",
        "date_sub",
        "date_diff",
        "date_interval_create_from_date_string",
        "date_modify",
        "date_timezone_get",
        "date_timezone_set",
        
        // Math functions
        "abs",
        "ceil",
        "floor",
        "round",
        "min",
        "max",
        "rand",
        "mt_rand",
        "random_int",
        "pow",
        "sqrt",
        "sin",
        "cos",
        "tan",
        "pi",
        
        // Laravel specific helper functions
        "app",
        "auth",
        "config",
        "env",
        "view",
        "abort",
        "redirect",
        "response",
        "request",
        "session",
        "cache",
        "trans",
        "back",
        "with",
        "collect",
        "now",
        "today",
        "route",
        "url",
        "asset"
    ])
);
